PROTECTED_TERMS = [
    "a/b testing",
    "accuracy",
    "activation function",
    "adaboost",
    "adagrad",
    "adam",
    "adam optimizer",
    "airflow",
    "anova",
    "arima",
    "attention mechanism",
    "auc",
    "autocorrelation",
    "autoencoder",
    "backpropagation",
    "bag of words",
    "batch normalization",
    "bayesian inference",
    "bayesian optimization",
    "bert",
    "bias",
    "bigquery",
    "binomial distribution",
    "central limit theorem",
    "chi-squared test",
    "cnn",
    "collaborative filtering",
    "confidence interval",
    "confusion matrix",
    "content-based filtering",
    "control group",
    "convolutional neural network",
    "correlation coefficient",
    "cosine annealing",
    "covariance",
    "cross-validation",
    "data augmentation",
    "data cleaning",
    "data drift",
    "data imbalance",
    "data preprocessing",
    "dbscan",
    "decision tree",
    "deep learning",
    "dependency parsing",
    "determinant",
    "dot product",
    "dropout",
    "dvc",
    "early stopping",
    "eigenvalue",
    "eigenvector",
    "encoder-decoder",
    "entropy",
    "ethics in ai",
    "expectation maximization",
    "experiment design",
    "exploding gradient",
    "exponential smoothing",
    "f1 score",
    "fairness",
    "false negative",
    "false positive rate",
    "fasttext",
    "feature engineering",
    "feature scaling",
    "feature selection",
    "few-shot learning",
    "forecasting",
    "gan",
    "gated recurrent unit",
    "gaussian distribution",
    "generative adversarial network",
    "glove",
    "gpt",
    "gradient",
    "gradient boosting",
    "gradient clipping",
    "gradient descent",
    "granger causality",
    "grid search",
    "gru",
    "hadoop",
    "hessian",
    "hidden markov model",
    "hierarchical clustering",
    "huggingface transformers",
    "hyperparameter tuning",
    "hypothesis testing",
    "jacobian",
    "k-means",
    "k-nearest neighbors",
    "keras",
    "kernel trick",
    "knn",
    "label encoding",
    "lag features",
    "language generation",
    "language model",
    "lasso regression",
    "latent dirichlet allocation",
    "lda",
    "lda topic model",
    "learning rate",
    "learning rate decay",
    "lemmatization",
    "lightgbm",
    "lime",
    "linear algebra",
    "linear regression",
    "logistic regression",
    "long short-term memory",
    "loss function",
    "lstm",
    "machine translation",
    "matplotlib",
    "matrix inversion",
    "maximum likelihood estimation",
    "mean",
    "median",
    "mini-batch gradient descent",
    "mlflow",
    "mode",
    "model drift",
    "model explainability",
    "model interpretability",
    "model monitoring",
    "momentum",
    "mongodb",
    "moving average",
    "multi-head attention",
    "mutual information",
    "naive bayes",
    "named entity recognition",
    "ner",
    "nesterov",
    "neural network",
    "normal distribution",
    "nosql",
    "numpy",
    "one hot encoding",
    "orthogonality",
    "overfitting",
    "p-value",
    "pandas",
    "pca",
    "pearson correlation",
    "pipeline",
    "poisson distribution",
    "pos tagging",
    "postgresql",
    "precision",
    "principal component analysis",
    "pytorch",
    "qda",
    "random forest",
    "random search",
    "recall",
    "recommender system",
    "recurrent neural network",
    "regularization",
    "relu",
    "resampling",
    "ridge regression",
    "rmsprop",
    "rnn",
    "roc curve",
    "scheduler",
    "scikit-learn",
    "seaborn",
    "seasonal decomposition",
    "semantic similarity",
    "sentiment analysis",
    "sequence labeling",
    "shap values",
    "sigmoid",
    "smote",
    "softmax",
    "spark",
    "sql",
    "standard deviation",
    "stationarity",
    "statistical significance",
    "stemming",
    "stochastic gradient descent",
    "stratified sampling",
    "support vector machine",
    "svr",
    "t-distribution",
    "tanh",
    "tensorflow",
    "tf-idf",
    "time series",
    "tokenization",
    "topic modeling",
    "train test split",
    "transformer",
    "treatment group",
    "true negative",
    "true positive rate",
    "underfitting",
    "uniform distribution",
    "vanishing gradient",
    "variance",
    "variational autoencoder",
    "vector norm",
    "weight initialization",
    "word embedding",
    "word2vec",
    "xgboost",
    "z-score",
    "zero-shot learning",
]
