version: '3.8'

services:
  ollama:
    build: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always

  whisper:
    build: ./whisper
    ports:
      - "6000:6000"
    restart: always

  assistant:
    build: ./assistant
    ports:
      - "5000:5000"
    depends_on:
      - ollama
      - whisper
    environment:
      - OLLAMA_URL=http://ollama:11434
      - WHISPER_URL=http://whisper:6000
    restart: always
    volumes:
      - ./assistant:/app

volumes:
  ollama:
