version: "3.9"

services:
  retroarch:
    build: .
    container_name: retroarch
    volumes:
      - ./roms/arcade:/roms
    ports:
      - "8080:8080"
    # devices:
    #   - /dev/input/js0:/dev/input/js0
    # restart: unless-stopped
