version: "3.9"

services:
  emulatorjs:
    image: docker.io/linuxserver/emulatorjs
    container_name: emulatorjs
    ports:
      - "8080:80"  # Access EmulatorJS in browser at http://localhost:8080
    volumes:
      - ./roms:/config/roms:Z   # ":Z" for SELinux compatibility
    restart: unless-stopped
