
version: '3.8'

services:
  interview-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview-assistant-whisper-container
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - whisper_models:/app/whisper_models
    environment:
      - FLASK_ENV=development
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: interview-assistant-ollama-container
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
  whisper_models:
