services:
  summarize-app:
    build: .
    image: summarizer-img
    container_name: summarizer-container
    volumes:
      - ./app:/app  # Mount export folder to save export on the host
#    environment:
#      - PYTHONUNBUFFERED=1
    container_name: summarizer_app_container
    # restart: on-failure
    command: ["tail", "-f", "/dev/null"] #the container stay idle and execute commands manually
