services:
  rstudio:
    build: .
    image: rstudio-img
    container_name: rstudio-container
    ports:
      - "8787:8787"
    environment:
      PASSWORD: rstudio
      ROOT: "TRUE"
      RUNROOTLESS: "FALSE"
    volumes:
      - ./data:/home/rstudio:rw
    tmpfs:
      - /var/run
      - /run
    privileged: true
    restart: unless-stopped
