Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('APPLICATION_CONFIGURATION','Whether the applications are on seperate databases. Possible values SINGLE_DB, DOUBLE_DB','SINGLE_DB');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('AUTHORITY_URL','ULR for notifying AIE in case of request received.','http://localhost:7003/aie-msgapp/notify');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('IMP_URL','URL for notifying IMP in case of Ack received','http://localhost:7003/crg-msgapp/notify');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('PROVIDER_INTERFACE','The provider interface endpoint for the SSN-EIS','http://localhost:7003/aie-msgapp/service');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('REPLY_URI','The Value for ReplyUri element','http://localhost:7003/crg-msgapp/message');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('IMDATE_SERVICES_URL','IMDATE services interface','http://demo2435837.mockable.io/imdatews');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('NSW_VERSION','The version for the NSW application','1.0.0');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('NSW_AUTHORITY','The Authority for the National Single Window application','GRPIR01');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('MODE','Acknowledgement of a  request for clearance depends on the clearance model adopted by the NSW','SYSTEMATIC');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('XML_AUTHORITY_URL','Authority URL for dispatching the original request for clearance message','http://localhost:7003/aie-msgapp/message');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_ARCGIS_SERVER_URL','ArcGis server URL','http://emsa-vms.athens.intrasoft-intl.private:8399');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_WMSCMAP_SERVER_URL','WMS C-MAP server URL','http://nms.emsa.europa.eu/geoserver/wms');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_MAX_NUM_LOCATE_RESULTS','The number of results displayed in the locate popup','10');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_STATIC_CONTENT_LIFETIME','The expiration time in seconds for the static content cache','600');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_MAX_NUM_FILTERS','Maximum number of GIS user filters','25');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_MAX_NUM_CONFIGURATIONS','Maximum number of GIS user configurations','10');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_VESSEL_PICTURES_URL','URL to query to fetch Vessel Pictures','http://photos.marinetraffic.com/ais/showphoto.aspx');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_LOCATE_ZOOM_LEVEL','The basemap level to zoom into when locating tracks ','11');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_ARCGIS_SERVER_PATH','ArcGis server Rest Path','arcgis/rest/services');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('EIS_LOCATION_SERVICE','URL of SSN service for requesting locations','http://isa0775.athens.intrasoft-intl.private:7013/ssn-location-ws/ssnlocationservice');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('EIS_URL','URL for sending MS2SSN_PortPlus_Not messages','http://isa0775.athens.intrasoft-intl.private:7023/ssn-xmlprotocol-v3-ws/ssnmessageservice');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('DATA_SUBSCRIBER_SERVICE','The DataSubscriberLocatinoService and DataSubscriberShipService','http://isa0775.athens.intrasoft-intl.private:7003');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('SHIPCALL_STATUS_UPDATE_TM','Defines the time that the ShipCall update status process will execute for teh departure voyages. Executes on a dialy basis.','23:00:00');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('SSN_GI_ESI_URL','SSN-GI external-systems interface URL','http://impsystem1.athens.intrasoft-intl.private:8080/ssn-gi/esi.json');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('GIS_INTERFACE','URL for opening a NSW-GI window','/nsw-gi/index.jsp?vessel=%s&nswLink=%s@%s&nswLink=%s@%s&nswLink=%s@%s&nswLink=%s@%s&nswLink=%s@%s');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('SSN_GI_ESI_USER','The username to be used when accessing the SSN-GI external-systems interface','SSNADMIN');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('EIS_SHIP_SERVICE','URL of SSN service for requesting ship particulars','http://isa0775.athens.intrasoft-intl.private:7013/ssn-shipparticulars-ws/ssnvesselservice');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('xmlSender_proxyHost','Proxy for ACK messages','localhost');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('xmlSender_proxyPort','Proxy port for ACK messages','80');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('URL_START_FOR_PROXY','URL start for proxy','http://http2https.');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('SEND_CREW_PAX_INFO','Determines whether Crew&Pax info will be sent to SSN upon request for details regarding Crew and Passengers from SSN.','true');
Insert into APPLICATION_PARAMETERS (CODE,COMMENTS,VALUE) values ('TBL_DATAFILE_PATH','Database datafile path','tes_data_file_path');
