Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('AbleSeaman','Able Seaman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Agent','Agent');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('AsstFoodBevMngr','Assitant Food and Beverage Manager');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('BarManager','Bar Manager');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('BarService','Bar Service');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Bosun','Bosun');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Cadet','Cadet');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Captain','Captain');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CargoTechnician','Cargo Technician');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CasinoStaff','Casino Staff');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefCook','Chief Cook');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefElectrician','Chief Electrician');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefHousekeeper','Chief Housekeeper');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefEngineer','Chief Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefMaster','Chief Master');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefMate','Chief Mate');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefOfficer','Chief Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefPurser','Chief Purser');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ChiefSteward','Chief Steward');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ClassSurveyor','Class Surveyor');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CSO','Company Security Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Cook','Cook');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CraneOperator','Crane Operator');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CrewMember','Crew Member');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CruiseDirector','Cruise Director');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('CruiseStaff','Cruise Staff');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('DeckApprentice','Deck Apprentice');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('DeckFitter','Deck Fitter');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('DeckOfficer','Deck Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Deckhand','Deckhand, Deck Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Doctor','Doctor');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Donkeyman','Donkeyman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ElectricalEngineer','Electrical Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ElectricalOfficer','Electrical Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Electrician','Electrician');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('EngineerCadet','Engineer Cadet, Engine Apprentice');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('EngineeringCrew','Engineering Crew, Engine Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('EngineFitter','Engine Fitter');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Entertainment','Entertainment');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FacilitiesCrew','Facilities Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FacilitiesManager','Facilities Manager');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FirstAsstEngineer','First Assistant Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FirstEngineer','First Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FirstMate','First Mate');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FirstOfficer','First Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Fitter','Fitter');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FourthOfficer','Fourth Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FoodBevMngr','Food and Beverage Manager, Catering Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FoodService','Food Service, Catering Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('FourthAsstEngineer','Fourth Assistant Engineer, Fourth Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Greaser','Greaser');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Hospitality','Hospitality');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('HotelDirector','Hotel Director');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('HotelStaff','Hotel Staff');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('HousekeepingStaff','Housekeeping Staff');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('InformationTechnology','Information Technology');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('JuniorEngineer','Junior Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('LaundryMaster','Laundry Master');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Lifeboatman','Lifeboatman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Maitred','Maitre d''');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('MarineCrew','Marine Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('MarketingRevenueMngr','Marketing Revenue Manager');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Master','Master');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('MasterFirstClassPilot','Master First Class Pilot');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('MateFirstClassPilot','Mate First Class Pilot');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Mechanic','Mechanic');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('MedicalStaff','Medical Staff');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Messman','Messman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Motorman','Motorman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Oiler','Oiler');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Operator','Operator');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('OrdinarySeaman','Ordinary Seaman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Owner','Owner');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Painter','Painter');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Porter','Porter');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Provision','Provision');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ProvisionMaster','Provision Master');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Pumpman','Pumpman, Pump Man');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('QMED','QMED');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('RadioOfficer','Radio Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Reeferman','Reeferman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Repairman','Repairman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('RiddingCrew','Ridding Crew');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('SafetyAndSecurity','Safety and Security');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('SecondAsstEngineer','Second Assistant Engineer, Second Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('SecondMate','Second Mate');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('SecondOfficer','Second Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('SSO','Ship Security Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('StaffCaptain','Staff Captain');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Steward','Steward');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Superintendent','Superintendent');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Tankerman','Tankerman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ThirdAsstEngineer','Third Assistant Engineer, Third Engineer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ThirdMate','Third Mate');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ThirdOfficer','Third Officer');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('ThirdParty','Third Party');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('TruckMechanic','Truck Mechanic');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Tunnelman','Tunnelman');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('UtilityPerson','Utility Person');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('VettingInspector','Vetting inspector');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Welder','Welder');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Wiper','Wiper');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('YardPersonnel','Yard Personnel');
Insert into CREW_DUTIES (CODE,DESCRIPTION) values ('Other','Other');
