Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('423','AZ','Azerbaijani Republic','images/flags/aj-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('425','IQ','Iraq (Republic of)','images/flags/iq-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('431','JP','Japan','images/flags/ja-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('432','JP','Japan','images/flags/ja-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('434','TM','Turkmenistan','images/flags/tx-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('437','UZ','Uzbekistan (Republic of)','images/flags/uz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('440','KR','Korea (Republic of)','images/flags/kn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('441','KR','Korea (Republic of)','images/flags/ks-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('445','KP','Democratic People''s Republic of Korea','images/flags/kn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('450','LB','Lebanon','images/flags/le-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('455','MV','Maldives','images/flags/mv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('457','MN','Mongolia','images/flags/mg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('459','NP','Nepal','images/flags/np-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('461','OM','Oman (Sultanate of)','images/flags/mu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('466','QA','Qatar (State of)','images/flags/qa-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('470','AE','United Arab Emirates','images/flags/ue-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('414','CN','China (People''s Republic of)','images/flags/ch-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('566','SG','Singapore (Republic of)','images/flags/sn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('472','TJ','Tajikistan (Republic of)','images/flags/tj-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('620','KM','Comoros (Union of the)','images/flags/km-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('229','MT','Malta','images/flags/mt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('373','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('577','VU','Vanuatu (Republic of)','images/flags/nh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('443','PS','Palestine','images/flags/palestine.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('473','YE','Yemen (Republic of)','images/flags/ym-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('477','HK','Hong Kong','images/flags/hk.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('478','BA','Bosnia and Herzegovina','images/flags/bosnia.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('503','AU','Australia','images/flags/at-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('506','MM','Myanmar (Union of)','images/flags/mm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('510','FM','Micronesia ','images/flags/fm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('512','NZ','New Zealand','images/flags/tk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('514','KH','Cambodia (Kingdom of)','images/flags/kh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('516','CX','Christmas Island (Indian Ocean)','images/flags/kt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('520','FJ','Fiji (Republic of)','images/flags/fj-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('523','CC','Cocos (Keeling) Islands','images/flags/ck-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('529','KI','Kiribati (Republic of)','images/flags/kr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('533','MY','Malaysia','images/flags/my-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('536','MP','Northern Mariana Islands (Commonwealth of the)','images/flags/cq-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('542','NU','Niue','images/flags/nu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('544','NR','Nauru (Republic of)','images/flags/nr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('548','PH','Philippines (Republic of the)','images/flags/ph-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('555','PN','Pitcairn Island','images/flags/pn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('559','AS','American Samoa','images/flags/aq-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('561','WS','Samoa (Independent State of)','images/flags/ws-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('564','SG','Singapore (Republic of)','images/flags/sn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('567','TH','Thailand','images/flags/th-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('570','TO','Tonga (Kingdom of)','images/flags/tn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('578','WF','Wallis and Futuna Islands','images/flags/yt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('603','AO','Angola (Republic of)','images/flags/ao-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('607',null,'Saint Paul and Amsterdam Islands','images/flags/frsouth.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('609','BI','Burundi (Republic of)','images/flags/bi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('611','BW','Botswana (Republic of)','images/flags/bc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('612','CF','Central African Republic','images/flags/ct-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('615','CG','Congo (Republic of the)','images/flags/cf-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('617','CV','Cape Verde (Republic of)','images/flags/cv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('619','CI','Cote d''Ivoire (Republic of)','images/flags/iv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('627','GH','Ghana','images/flags/gh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('655','MW','Malawi','images/flags/mi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('0',null,null,'images/flags/none.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('999',null,null,'images/flags/none.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('621','DJ','Djibouti (Republic of)','images/flags/dj-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('622','EG','Egypt (Arab Republic of)','images/flags/eg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('624','ET','Ethiopia (Federal Democratic Republic of)','images/flags/et-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('626','GA','Gabonese Republic','images/flags/gb-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('629','GM','Gambia (Republic of the)','images/flags/ga-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('630','GW','Guinea-Bissau (Republic of)','images/flags/gn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('631','GQ','Equatorial Guinea (Republic of)','images/flags/ek-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('632','GN','Guinea (Republic of)','images/flags/gv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('633','BF','Burkina Faso','images/flags/uv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('634','KE','Kenya (Republic of)','images/flags/ke-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('635',null,'Kerguelen Islands','images/flags/frsouth.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('636','LR','Liberia (Republic of)','images/flags/lr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('637','LR','Liberia (Republic of)','images/flags/lr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('642','LY','Socialist People''s Libyan Arab Jamahiriya','images/flags/ly-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('644','LS','Lesotho (Kingdom of)','images/flags/ls-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('645','MU','Mauritius (Republic of)','images/flags/mp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('647','MG','Madagascar (Republic of)','images/flags/ma-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('649','ML','Mali (Republic of)','images/flags/ml-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('650','MZ','Mozambique (Republic of)','images/flags/mz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('654','MR','Mauritania (Islamic Republic of)','images/flags/mr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('656','NE','Niger (Republic of the)','images/flags/ne-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('657','NG','Nigeria (Federal Republic of)','images/flags/ng-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('659','NA','Namibia (Republic of)','images/flags/wa-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('660','RE','Reunion (French Department of)','images/flags/wf-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('661','RW','Rwanda (Republic of)','images/flags/rwanda-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('662','SD','Sudan (Republic of the)','images/flags/sd-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('663','SN','Senegal (Republic of)','images/flags/sg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('664','SC','Seychelles (Republic of)','images/flags/se-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('665','SH','Saint Helena','images/flags/sh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('666','SO','Somali Democratic Republic','images/flags/so-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('667','SL','Sierra Leone','images/flags/sl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('668','ST','Sao Tome and Principe (Democratic Republic of)','images/flags/tp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('669','SZ','Swaziland (Kingdom of)','images/flags/wz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('670','TD','Chad (Republic of)','images/flags/cd-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('671','TG','Togolese Republic','images/flags/to-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('672','TN','Tunisia','images/flags/ts-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('674','TZ','Tanzania (United Republic of)','images/flags/tz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('675','UG','Uganda (Republic of)','images/flags/ug-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('676','CD','Democratic Republic of the Congo','images/flags/cf-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('677','TZ','Tanzania (United Republic of)','images/flags/tz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('678','ZM','Zambia (Republic of)','images/flags/za-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('679','ZW','Zimbabwe (Republic of)','images/flags/zi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('701','AR','Argentine Republic','images/flags/ar-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('710','BR','Brazil (Federative Republic of)','images/flags/br-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('720','BO','Bolivia (Republic of)','images/flags/bl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('725','CL','Chile','images/flags/cl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('730','CO','Colombia (Republic of)','images/flags/co-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('735','EC','Ecuador','images/flags/ec-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('740','FK','Falkland Islands (Malvinas)','images/flags/fk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('745','GY','Guiana (French Department of)','images/flags/fr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('750','GY','Guyana','images/flags/gy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('755','PY','Paraguay (Republic of)','images/flags/py-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('765','SR','Suriname (Republic of)','images/flags/sr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('770','UY','Uruguay (Eastern Republic of)','images/flags/uy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('775','VE','Venezuela (Bolivarian Republic of)','images/flags/ve-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('237','GR','Greece','images/flags/gr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('240','GR','Greece','images/flags/gr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('242','MA','Morocco (Kingdom of)','images/flags/mo-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('244','NL','Netherlands','images/flags/nl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('246','NL','Netherlands','images/flags/nl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('248','MT','Malta','images/flags/mt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('249','MT','Malta','images/flags/mt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('250','IE','Ireland','images/flags/ie-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('251','IS','Iceland','images/flags/ic-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('253','LU','Luxembourg','images/flags/lu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('254','MC','Monaco (Principality of)','images/flags/mn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('256','MT','Malta','images/flags/mt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('261','PL','Poland (Republic of)','images/flags/pl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('264','RO','Romania','images/flags/ro-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('265','SE','Sweden','images/flags/sw-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('266','SE','Sweden','images/flags/sw-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('267','SK','Slovak Republic','images/flags/sk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('269','CH','Switzerland (Confederation of)','images/flags/sz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('271','TR','Turkey','images/flags/tu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('272','UA','Ukraine','images/flags/up-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('274','MK','The Former Yugoslav Republic of Macedonia','images/flags/mk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('277','LT','Lithuania (Republic of)','images/flags/lh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('279','RS','Serbia (Republic of)','images/flags/yu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('301','AI','Anguilla','images/flags/av-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('305','AG','Antigua and Barbuda','images/flags/ac-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('307','AW','Aruba','images/flags/aa-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('308','BS','Bahamas (Commonwealth of the)','images/flags/bahamas_flag-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('310','BM','Bermuda','images/flags/bd-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('312','BZ','Belize','images/flags/bz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('314','BB','Barbados','images/flags/bb-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('201','AL','Albania (Rebublic of)','images/flags/al-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('202','AD','Andorra (Principality of)','images/flags/an-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('203','AT','Austria','images/flags/au-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('204','PT','Azores','images/flags/po-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('205','BE','Belgium','images/flags/be-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('206','BY','Belarus (Republic of)','images/flags/bo-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('241',null,'Greece','images/flags/gr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('207','BG','Bulgaria (Republic of)','images/flags/bu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('208','VA','Vatican City State','images/flags/vt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('209','CY','Cyprus (Republic of)','images/flags/cy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('210','CY','Cyprus (Republic of)','images/flags/cy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('211','DE','Germany (Federal Republic of)','images/flags/de-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('212','CY','Cyprus (Republic of)','images/flags/cy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('213','GE','Georgia','images/flags/gg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('214','MD','Moldova (Republic of)','images/flags/md-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('215','MT','Malta','images/flags/mt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('216','AM','Armenia (Republic of)','images/flags/am-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('218','DE','Germany (Federal Republic of)','images/flags/de-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('219','DK','Denmark','images/flags/da-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('220','DK','Denmark','images/flags/da-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('224','ES','Spain','images/flags/sp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('225','ES','Spain','images/flags/sp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('226','FR','France','images/flags/fr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('227','FR','France','images/flags/fr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('228','FR','France','images/flags/fr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('230','FI','Finland','images/flags/fi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('231','FO','Faroe Islands','images/flags/fo.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('232','GB','United Kingdom of Great Britain and Northern Ireland','images/flags/uk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('233','GB','United Kingdom of Great Britain and Northern Ireland','images/flags/uk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('234','GB','United Kingdom of Great Britain and Northern Ireland','images/flags/uk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('235','GB','United Kingdom of Great Britain and Northern Ireland','images/flags/uk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('236','GI','Gibraltar','images/flags/gi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('238','HR','Croatia (Republic of)','images/flags/hr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('239','GR','Greece','images/flags/gr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('243','HU','Hungary (Republic of)','images/flags/hu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('245','NL','Netherlands','images/flags/nl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('247','IT','Italy','images/flags/it-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('574','VN','Viet Nam (Socialist Republic of)','images/flags/vm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('252','LI','Liechtenstein (Principality of)','images/flags/li-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('255','PT','Madeira','images/flags/po-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('257','NO','Norway','images/flags/no-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('258','NO','Norway','images/flags/no-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('259','NO','Norway','images/flags/no-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('263','PT','Portugal','images/flags/po-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('268','SM','San Marino (Republic of)','images/flags/sm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('270','CZ','Czech Republic','images/flags/ez-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('273','RU','Russian Federation','images/flags/ru-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('275','LV','Latvia (Republic of)','images/flags/lg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('276','EE','Estonia (Republic of)','images/flags/en-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('278','SI','Slovenia (Republic of)','images/flags/si-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('303','US','Alaska (State of)','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('262',null,null,'images/flags/none.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('372','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('760','PE','Peru (Republic of)','images/flags/pe-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('304','AG','Antigua and Barbuda','images/flags/ac-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('306','AN','Netherlands Antilles','images/flags/nt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('309','BS','Bahamas (Commonwealth of the)','images/flags/bahamas_flag-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('311','BS','Bahamas (Commonwealth of the)','images/flags/bahamas_flag-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('321','CR','Costa Rica','images/flags/cs-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('327','DO','Dominican Republic','images/flags/dr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('330','GD','Grenada','images/flags/gd-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('334','HN','Honduras (Republic of)','images/flags/hn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('338','US','United States of America','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('343','LC','Saint Lucia','images/flags/st-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('345','MX','Mexico','images/flags/mx-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('348','MS','Montserrat','images/flags/ms-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('351','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('352','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('353','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('354','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('355','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('356','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('357','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('370','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('361','PM','Saint Pierre and Miquelon (Territorial Collectivit','images/flags/st_pierre_and_miquelon-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('364','TC','Turks and Caicos Islands','images/flags/turks_caicos-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('367','US','United States of America','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('369','US','United States of America','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('376','VC','Saint Vincent and the Grenadines','images/flags/vc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('377','VC','Saint Vincent and the Grenadines','images/flags/vc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('401','AF','Afghanistan','images/flags/af-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('405','BD','Bangladesh (People''s Republic of)','images/flags/bg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('410','BT','Bhutan (Kingdom of)','images/flags/bt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('413','CN','China (People''s Republic of)','images/flags/ch-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('417','LK','Sri Lanka (Democratic Socialist Republic of)','images/flags/ce-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('422','IR','Iran (Islamic Republic of)','images/flags/ir-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('428','IL','Israel (State of)','images/flags/is-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('436','KZ','Kazakhstan (Republic of)','images/flags/kz-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('438','JO','Jordan (Hashemite Kingdom of)','images/flags/jo-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('447','KW','Kuwait (State of)','images/flags/kw-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('451','KG','Kyrgyz Republic','images/flags/kg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('453','MO','Macao','images/flags/mc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('463','PK','Pakistan (Islamic Republic of)','images/flags/pk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('468','SY','Syrian Arab Republic','images/flags/sy-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('475','YE','Yemen (Republic of)','images/flags/ym-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('501',null,'Adelie Land','images/flags/frsouth.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('508','BN','Brunei Darussalam','images/flags/bx-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('511','PW','Palau ','images/flags/ps-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('515','KH','Cambodia (Kingdom of)','images/flags/kh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('518','CK','Cook Islands','images/flags/cw-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('525','ID','Indonesia (Republic of)','images/flags/id-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('531','LA','Lao People''s Democratic Republic','images/flags/la-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('538','MH','Marshall Islands (Republic of the)','images/flags/rm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('540','NC','New Caledonia','images/flags/yt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('546','PF','French Polynesia','images/flags/pf-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('553','PG','Papua New Guinea','images/flags/pg-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('557','SB','Solomon Islands','images/flags/bp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('563','SG','Singapore (Republic of)','images/flags/sn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('565','SG','Singapore (Republic of)','images/flags/sn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('572','TV','Tuvalu','images/flags/tv-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('576','VU','Vanuatu (Republic of)','images/flags/nh-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('601','ZA','South Africa (Republic of)','images/flags/sf-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('605','DZ','Algeria (People''s Democratic Republic of)','images/flags/ag-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('608',null,'Ascension Island','images/flags/uk-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('610','BJ','Benin (Republic of)','images/flags/bn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('613','CM','Cameroon (Republic of)','images/flags/cm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('616','KM','Comoros (Union of the)','images/flags/cn-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('618',null,'Crozet Archipelago','images/flags/frsouth.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('625','ER','Eritrea','images/flags/er-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('316','CA','Canada','images/flags/ca-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('319','KY','Cayman Islands','images/flags/ky-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('323','CU','Cuba','images/flags/cu-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('325','DM','Dominica (Commonwealth of)','images/flags/do-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('329','GP','Guadeloupe (French Department of)','images/flags/gp-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('331','GL','Greenland','images/flags/gl-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('332','GT','Guatemala (Republic of)','images/flags/gt-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('336','HT','Haiti (Republic of)','images/flags/ha-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('339','JM','Jamaica','images/flags/jm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('341','KN','Saint Kitts and Nevis (Federation of)','images/flags/sc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('347','MQ','Martinique (French Department of)','images/flags/mb-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('350','NI','Nicaragua','images/flags/ni-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('358','PR','Puerto Rico','images/flags/pr-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('359','SV','El Salvador (Republic of)','images/flags/es-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('362','TT','Trinidad and Tobago','images/flags/td-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('366','US','United States of America','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('368','US','United States of America','images/flags/us-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('371','PA','Panama (Republic of)','images/flags/pm-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('375','VC','Saint Vincent and the Grenadines','images/flags/vc-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('378','VG','British Virgin Islands','images/flags/vi-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('379','VI','United States Virgin Islands','images/flags/vq-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('403','SA','Saudi Arabia (Kingdom of)','images/flags/sa-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('408','BH','Bahrain (Kingdom of)','images/flags/ba-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('412','CN','China (People''s Republic of)','images/flags/ch-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('416','TW','Taiwan (Province of China)','images/flags/tw-t.gif');
Insert into MNG_MID (DIGITS,COUNTRY_CODE,COUNTRY_NAME,COUNTRY_FLAG) values ('419','IN','India (Republic of)','images/flags/in-t.gif');
