Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (1,'CARGO_PROVIDE','Permission to provide Cargo Declaration and DPG data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (2,'CARGO_CONSULT','Permission to read Cargo Declaration and DPG data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (3,'CARGO_CLEARANCE','Permission to provide approval or denial of clearance for Cargo Declaration and DPG group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (4,'PORT_CLEARANCE','Permission to approve or not Port Call data.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (5,'LIABILITY_CERTIFICATES_CONSULT','Permission to read Civil Liability Certificate for Oil and Bunker Oil Pollution Damage data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (6,'AGENCY_MANAGE','Manage agency definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (7,'MAPVIEW','Permission to access the GIS map graphical interface.','GI');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (8,'ARRIVAL_CUSTOMS_CONSULT','Permission to read Customs arrival notification details data group elements','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (9,'ARRIVAL_CUSTOMS_PROVIDE','Permission to provide Customs arrival notification details data group elements','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (10,'USER_MANAGE','Manage user accounts.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (11,'PROFILE_MANAGE','Manage profile definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (12,'REQULATORY_INFO_MANAGE','Manage requelatory information by defining the groups of data elements of interest to the NSW.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (13,'SHIP_MANAGE','Manage ship definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (14,'SHIPPING_COMPANY_MANAGE','Manage shipping companies.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (15,'LOCATION_MANAGE','Manage location definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (16,'AREA_MANAGE','Manage area definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (17,'SHIP_IDENTIFICATION_PROVIDE','Permission to provide Ship identification data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (18,'SHIP_PARTICULARS_PROVIDE','Permission to provide Ship particulars data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (19,'PORT_CALL_PROVIDE','Permission to provide Port call data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (20,'PRE_ARRIVAL_PROVIDE','Permission to provide Pre-arrival 72 hour data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (21,'ARRIVAL_PROVIDE','Permission to provide Arrival data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (22,'DEPARTURE_PROVIDE','Permission to provide Departure data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (23,'VOYAGE_PROVIDE','Permission to provide Voyage data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (24,'DPG_PROVIDE','Permission to provide Dangerous and poluting goods data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (25,'DPG_ITEMS_PROVIDE','Permission to provide Dangerous and poluting goods items data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (26,'SHIP_STORES_PROVIDE','Permission to provide Ship stores data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (27,'WASTE_PROVIDE','Permission to provide Waste data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (28,'WASTE_DISPOSAL_PROVIDE','Permission to provide Waste disposal information data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (29,'SECURITY_PROVIDE','Permission to provide Security data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (30,'NPOB_PROVIDE','Permission to provide Number of persons on board data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (31,'PASSENGERS_PROVIDE','Permission to provide Passengers data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (32,'CREW_PROVIDE','Permission to provide Crew data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (33,'CREW_EFFECTS_PROVIDE','Permission to provide Crew effects data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (34,'HEALTH_PROVIDE','Permission to provide Health data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (35,'HEALTH_MDH_PROVIDE','Permission to provide Health - MDH Attachment data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (36,'SHIP_IDENTIFICATION_CONSULT','Permission to read Ship identification data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (37,'SHIP_PARTICULARS_CONSULT','Permission to read Ship particulars data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (38,'PORT_CALL_CONSULT','Permission to read Port call data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (39,'PRE_ARRIVAL_CONSULT','Permission to read Pre-arrival 72 hour data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (40,'ARRIVAL_CONSULT','Permission to read Arrival data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (41,'DEPARTURE_CONSULT','Permission to read Departure data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (42,'VOYAGE_CONSULT','Permission to read Voyage data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (43,'DPG_CONSULT','Permission to read Dangerous and poluting goods data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (44,'DPG_ITEMS_CONSULT','Permission to read Dangerous and poluting goods items data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (45,'SHIP_STORES_CONSULT','Permission to read Ship stores data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (46,'WASTE_CONSULT','Permission to read Waste data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (47,'WASTE_DISPOSAL_CONSULT','Permission to read Waste disposal information data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (48,'SECURITY_CONSULT','Permission to read Security data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (49,'NPOB_CONSULT','Permission to read Number of persons on board data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (50,'PASSENGERS_CONSULT','Permission to read Passengers data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (51,'CREW_CONSULT','Permission to read Crew data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (52,'CREW_EFFECTS_CONSULT','Permission to read Crew effects data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (53,'HEALTH_CONSULT','Permission to read Health data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (54,'HEALTH_MDH_CONSULT','Permission to read Health - MDH Attachment data group element data.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (55,'WASTE_RECEIPT_PROVIDE','Permission to provide Waste delivery receipt data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (56,'BUNKERS_PROVIDE','Permission to provide Bunkers remaining on-board data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (57,'LIABILITY_CERTIFICATES_PROVIDE','Permission to provide Civil Liability Certificate for Oil and Bunker Oil Pollution Damage data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (58,'SHIP_DEFECTS_PROVIDE','Permission to provide Ship defects data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (59,'WASTE_RECEIPT_CONSULT','Permission to read Waste delivery receipt data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (60,'BUNKERS_CONSULT','Permission to read Bunkers remaining on-board data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (61,'DPG_CLEARANCE','Permission to provide approval or denial of clearance for Dangerous and poluting goods data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (62,'CREW_EFFECTS_CLEARANCE','Permission to provide approval or denial of Crew effects tab','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (63,'SHIP_STORES_CLEARANCE','Permission to provide approval or denial of clearance for Ship stores data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (64,'WASTE_CLEARANCE','Permission to provide approval or denial of clearance for Waste data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (65,'SHIP_DEFECTS_CONSULT','Permission to read Ship defects data group elements.','CRG');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (66,'SECURITY_CLEARANCE','Permission to provide approval or denial of clearance for Security data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (67,'WASTE_RECEIPT_CLEARANCE','Permission to provide acceptance or not of clearance for Waste delivery receipt data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (68,'BUNKERS_CLEARANCE','Permission to provide acceptance or not of clearance for Bunkers remaining on-board data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (69,'LIABILITY_CERTIFICATES_CLEARANCE','Permission to provide acceptance or not of clearance for Civil Liability Certificate for Oil and Bunker Oil Pollution Damage data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (70,'SHIP_DEFECTS_CLEARANCE','Permission to provide acceptance or not of clearance for Ship defects data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (71,'HEALTH_CLEARANCE','Permission to provide approval or denial of clearance for Health data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (72,'ATTACHMENT_TYPE_MANAGE','Manage attachment type definition.','RESOURCES');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (73,'SHIP_IDENTIFICATION_CLEARANCE','Permission to approve or not Ship identification and particular data.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (74,'NPOB_CLEARANCE','Permission to provide acceptance or not of clearance for Number of persons on board data group elements.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (75,'CREW_AND_PASSENGERS_CLEARANCE','Permission to provide approval or denial of Crew and Passengers tab.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (76,'CARGO_CONTROL_AGENT','Permission to provide acceptance of an ECTN message.','AIE');
Insert into MNG_PERMISSION (SID,NAME,DESCRIPTION,APPLICATION) values (77,'CARGO_AGENT','Permission to authorise an ECTN message.','AIE');
