-- Init user

-- Create profile
Insert into MNG_PROFILES (NAME,DESCRIPTION) values ('SUPER_USER','EMSW Super User');

-- Assign permissions to profile

Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',1);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',2);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',3);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',4);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',5);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',6);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',7);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',8);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',9);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',10);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',11);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',12);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',13);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',14);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',15);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',16);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',17);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',18);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',19);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',20);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',21);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',22);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',23);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',24);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',25);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',26);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',27);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',28);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',29);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',30);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',31);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',32);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',33);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',34);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',35);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',36);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',37);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',38);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',39);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',40);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',41);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',42);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',43);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',44);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',45);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',46);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',47);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',48);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',49);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',50);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',51);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',52);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',53);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',54);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',55);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',56);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',57);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',58);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',59);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',60);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',61);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',62);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',63);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',64);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',65);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',66);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',67);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',68);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',69);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',70);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',71);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',72);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',73);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',74);
Insert into MNG_PROFILE_PERMISSIONS (PROFILE_NAME,PERMISSION_SID) values ('SUPER_USER',75);

-- Create organisation

Insert into MNG_ORGANISATIONS (SID,AGENCY_NAME,BUSINESS_PHONE,CONTACT_EMAIL,CONTACT_FAX,COUNTRY_CODE,RESTRICTION_TYPE,RESTRICTION_VALUE) 
values (100404,'agent_one','2431035679','agent_one@gmail.com','2431035679','XX','COUNTRY',null);

-- Assign profile to organisation

Insert into MNG_ORGANISATION_PROFILES (ORGANISATION_SID,PROFILE_NAME) values (100404,'SUPER_USER');

-- Create user ECTNADMIN

Insert into MNG_USERS (SID,PERSON_FAMILY_NAME,PERSON_GIVEN_NAME,PASSWORD,USER_ID,BUSINESS_PHONE,CONTACT_EMAIL,CONTACT_FAX,ACTIVE_END_DT,
INTERFACE_TYPE,ENABLED,EMAIL_RECIPIENT,USER_LOCALE,LOGIN_TRIES_COUNTER,LOCKED,EXPIRES_ON,COUNTRY_CODE,ORGANISATION_SID) values 
(149215,'joanna','joanna','joanna1','joanna','697777777','ioanna.katsiouli@intrasoft-intl.com',null,null,0,true,true,'en',0,false,
to_date('2020-07-23', 'YYYY-MM-DD'),'GR',100404);

Insert into MNG_USERS (SID,PERSON_FAMILY_NAME,PERSON_GIVEN_NAME,PASSWORD,USER_ID,BUSINESS_PHONE,CONTACT_EMAIL,CONTACT_FAX,ACTIVE_END_DT,
INTERFACE_TYPE,ENABLED,EMAIL_RECIPIENT,USER_LOCALE,LOGIN_TRIES_COUNTER,LOCKED,EXPIRES_ON,COUNTRY_CODE,ORGANISATION_SID) values 
(14000,'ECTN ADMIN','ECTN ADMIN','ECTNADMIN1','ECTNADMIN','697777777','ioanna.katsiouli@intrasoft-intl.com',null,null,0,true,true,'en',0,false,
to_date('2020-07-23', 'YYYY-MM-DD'),'GR',100404);

