Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (50,'Vessel designed to carry general cargo.','General cargo vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (501,'Vessel designed to carry grain.','Grain vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (502,'Vessel designed to carry logs and timber.','Timber/log carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (503,'Vessel designed to carry wood chips.','Wood chips vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (504,'Vessel designed to carry steel products.','Steel products vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (505,'Vessel designed to carry general cargo and containers.','Carrier, general cargo/container');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (506,'Vessel designed to carry temperature-controlled cargo.','Temperature-controlled cargo vessels');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (51,'Vessel designed to carry unit loads.','Unit carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (511,'Vessel designed to carry containers only.','Full container ship/cellular vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (512,'Vessel with ramp designed to carry roll-on/roll-off cargo.','RORO vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (513,'Vessel designed to carry automotive vehicles or their knock-down parts.','Car carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (514,'Vessel designed to carry livestock.','Livestock carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (515,'Vessel designed to carry barges. Lash means lighters aboard ship.','Barge carrier – Lash ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (516,'Vessel designed to carry chemicals in bulk or drums not in tanks.','Chemical carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (517,'Vessel designed to carry irradiated fuel.','Irradiated fuel carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (518,'Ship designed to carry heavy cargo.','Heavy cargo vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (519,'Vessel designed to carry both containers and rollon/roll-off cargo.','RoRo/container vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (52,'Vessel designed to carry bulk cargo.','Bulk carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (521,'Vessel designed to carry dry bulk (expellers).','Dry bulk carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (522,'Vessel designed to carry ore.','Ore carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (523,'Vessel designed to carry cement.','Cement carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (524,'Vessel designed to carry gravel.','Gravel carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (525,'Vessel designed to carry coal.','Coal carrier');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (53,'Vessel solely equipped with tanks to carry cargo.','Tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (531,'Tanker designed to carry crude oil.','Crude oil tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (532,'Tanker designed to carry chemicals in coastal traffic.','Chemical tanker, coaster');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (533,'Tanker designed to carry chemicals in deep sea.','Chemical tanker, deep sea');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (534,'Tanker designed to carry oil and other derivatives.','Oil and other derivatives tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (54,'Tanker designed to carry liquefied gas.','Liquefied gas tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (541,'Vessel  designed  to  carry  Liquefied  Petroleum  Gas (LPG).','LPG tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (542,'Tanker designed to carry Liquefied Natural Gas (LNG).','LNG tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (543,'Tanker designed to carry Liquefied Natural Gas (LNG) and Liquefied Petroleum Gas (LPG).','LNG/LPG tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (55,'Tanker designed to carry other special liquids.','Other special tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (551,'Tanker designed to carry asphalt and bitumen.','Asphalt/bitumen tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (552,'Tanker designed to carry molasses.','Molasses tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (553,'Tanker designed to carry vegetable oil.','Vegetable oil tanker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (57,'Vessel designed to carry cargo and passengers.','Cargo and passenger vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (59,'Vessel designed to carry more than 12 passengers.','Passenger ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (591,'Passenger ship designed to carry tourists on specified routes.','Cruise ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (592,'Vessel designed to ply regularly between two or more ports.','Ferry');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (593,'Vessel  designed  to  carry  passengers,  not  otherwise specified.','Other passenger ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (594,'Vessel  designed  to  carry  passengers  and  mainly propelled by sails.','Passenger ship, sailing');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (60,'Vessel designed to give assistance.','Assistance vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (601,'Vessel designed to tow objects but sailing alone.','Tug, without tow');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (602,'Vessel designed to tow, and towing an object.','Tug, with tow');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (603,'Vessel designed to salvage.','Salvage vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (604,'Vessel designed to effect rescue operations.','Rescue vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (605,'Vessel designed to combat oil spills.','Oil combat vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (606,'Object designed for drilling oil at sea.','Oil rig');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (607,'Vessel designed to serve as a hospital at sea.','Hospital vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (70,'Sea-going vessel, not otherwise specified.','Other sea-going vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (711,'Vessel designed to convey pilots to/from ships.','Pilot boat');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (712,'Vessel designed to guard, patrol or measure.','Patrol/measure ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (72,'Vessel designed to assist in work.','Work ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (721,'Vessel designed to provide supplies.','Supply vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (723,'Vessel designed to provide offshore support.','Offshore support vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (724,'Flat-bottomed vessel with a flat deck.','Pontoon');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (725,'Vessel designed to dump stones.','Stone dumping vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (726,'Vessel designed to lay cable.','Cable layer');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (727,'Vessel designed to handle buoys.','Buoyage vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (728,'Vessel designed to break ice.','Icebreaker');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (729,'Vessel designed to lay pipe.','Pipelaying vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (73,'Vessel designed to push other vessels.','Push boat');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (74,'Vessel designed to scoop or suck mud or sand.','Dredger');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (75,'Vessel designed for fishing.','Fishing boat');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (751,'Vessel designed to drag a bag-like net.','Trawler');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (752,'Small vessel that sometimes can be carried on a larger ship.','Cutter');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (753,'Vessel designed as a fish factory.','Factory ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (76,'Vessel designed for research and education.','Research and education ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (761,'Vessel designed for fishery research.','Fishery research vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (762,'Vessel designed for climate registration.','Climate registration vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (763,'Vessel  designed  for  environmental  monitoring  and measurement.','Ship for environmental measurement');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (764,'Vessel designed for scientific purposes.','Scientific vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (765,'Vessel designed for training, powered by sail.','Sailing school ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (766,'Vessel designed for training.','Training vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (77,'Vessel operated by a navy.','Navy vessel');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (78,'Any floating structure.','Structure, floating');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (781,'A crane mounted on a barge or pontoon.','Crane, floating');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (782,'A submersible floating structure used as a dock.','Dock, floating');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (80,'Vessel designed for recreation.','Pleasure boat');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (81,'Vessel designed for speed, often used for recreation.','Speedboat');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (82,'Vessel  designed  primarily  for  sailing,  outfitted  with  an auxiliary motor.','Sailing boat with auxiliary motor');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (83,'A specific type of vessel mostly used for pleasure and designed for sailing.','Sailing yacht');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (84,'Vessel designed for sport fishing.','Boat for sport fishing');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (85,'Vessel longer than 20 metres, designed for recreation.','Craft, pleasure, longer than 20 metres');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (89,'Vessel    designed    for    recreation,    not    otherwise specified.','Craft, other, recreational');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (90,'Fast, all-purpose vessel.','Fast ship');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (91,'Vessel  with  wing-like  structure  for  skimming  at  high speed.','Hydrofoil');
Insert into SHIP_TYPES (CODE,DESCRIPTION,SHIP_TYPE) values (92,'Fast vessel designed with two parallel hulls.','Catamaran, fast');
